### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by sbims** [pipriles/fb-event-scraper#3]
Hello,

I'm looking for a piece of code to scrap some infos about fb events and this one looked perfect for me. But when I try to operate it, it successes to connect to fb and to extract data but after that it gives me these error lines.

Success!
Extracting place id...
https://www.facebook.com/labellevilloiseparis
Extracting events...
Extracting host: None 1
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/simonmallo/Desktop/Eventz/eventscraper/events.py", line 592, in <module>
    main()
  File "/Users/simonmallo/Desktop/Eventz/eventscraper/events.py", line 583, in main
    json_list = json_list + spider.expand_search()
  File "/Users/simonmallo/Desktop/Eventz/eventscraper/events.py", line 488, in expand_search
    raise(e)
  File "/Users/simonmallo/Desktop/Eventz/eventscraper/events.py", line 486, in expand_search
    self.scrape_pendings()
  File "/Users/simonmallo/Desktop/Eventz/eventscraper/events.py", line 447, in scrape_pendings
    if len(host) - count >= limit:
TypeError: object of type 'NoneType' has no len()

Anyone knows what is the problem ?

Thanks

**Comment by Slontse77** [comment]
> Hello,
> 
> I'm looking for a piece of code to scrap some infos about fb events and this one looked perfect for me. But when I try to operate it, it successes to connect to fb and to extract data but after that it gives me these error lines.
> 
> Success!
> Extracting place id...
> https://www.facebook.com/labellevilloiseparis
> Extracting events...
> Extracting host: None 1
> Expecting value: line 1 column 1 (char 0)
> Traceback (most recent call last):
> File "/Users/simonmallo/Desktop/Eventz/eventscraper/events.py", line 592, in
> main()
> File "/Users/simonmallo/Desktop/Eventz/eventscraper/events.py", line 583, in main
> json_list = json_list + spider.expand_search()
> File "/Users/simonmallo/Desktop/Eventz/eventscraper/events.py", line 488, in expand_search
> raise(e)
> File "/Users/simonmallo/Desktop/Eventz/eventscraper/events.py", line 486, in expand_search
> self.scrape_pendings()
> File "/Users/simonmallo/Desktop/Eventz/eventscraper/events.py", line 447, in scrape_pendings
> if len(host) - count >= limit:
> TypeError: object of type 'NoneType' has no len()
> 
> Anyone knows what is the problem ?
> 
> Thanks

Hi!
I have the same error.
Have you managed to fix it?
(or to find some other solution?)

Thank you!
